version: '3.3'

services:
  telegram_bot_api:
    image: almorbibadoc/telegram-bot-api:latest
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
    ports:
      - "8081:8081"
    networks:
      - bot_network
    restart: unless-stopped

  python_bot:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      API_TOKEN: ${API_TOKEN}
      LOCAL_API_URL: ${BOT_API:-http://telegram_bot_api:8081}
    depends_on:
      - telegram_bot_api
    networks:
      - bot_network
    restart: unless-stopped

networks:
  bot_network:
