version: '3.3'

services:
  vpn:
    image: bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TOKEN=${NORDVPN_TOKEN}
      - CONNECT=Netherlands
      - TECHNOLOGY=NordLynx
      - KILLSWITCH=enabled
      - DNS=1.1.1.1,8.8.8.8
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    networks:
      - bot_network
    logging:
      driver: "none"

  telegram_bot_api:
    build:
      context: .
      dockerfile: Dockerfile.telegram-bot
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
    depends_on:
      - vpn
    network_mode: "service:vpn"
    restart: unless-stopped

  python_bot:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      API_TOKEN: ${API_TOKEN}
      LOCAL_API_URL: http://localhost:8081
      MONGO_URI: mongodb://mongo:27017/telegram_bot_d
    depends_on:
      - mongo
      - telegram_bot_api
      - vpn
    network_mode: "service:vpn"
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bot_network
    command: mongod --quiet --logpath /dev/null

volumes:
  mongo_data:
    driver: local

networks:
  bot_network:
