version: '3.3'

services:
  vpn:
    image: bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TOKEN=${NORDVPN_TOKEN}
      - CONNECT=Netherlands
      - TECHNOLOGY=NordLynx
      - KILLSWITCH=enabled
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    networks:
      bot_network:
        ipv4_address: 172.20.0.2

  telegram_bot_api:
    build:
      context: .
      dockerfile: Dockerfile.telegram-bot
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
    depends_on:
      - vpn
    networks:
      bot_network:
        ipv4_address: 172.20.0.3
    restart: unless-stopped

  python_bot:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      API_TOKEN: ${API_TOKEN}
      NORDVPN_TOKEN: ${NORDVPN_TOKEN}
      LOCAL_API_URL: http://172.20.0.3:8081  # IP вместо имени контейнера
      MONGO_URI: mongodb://mongo:27017/telegram_bot_d
    depends_on:
      - mongo
      - telegram_bot_api
      - vpn
    networks:
      bot_network:
        ipv4_address: 172.20.0.4
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      bot_network:
        ipv4_address: 172.20.0.5
    command: mongod --quiet --logpath /dev/null

volumes:
  mongo_data:
    driver: local

networks:
  bot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
