services:
  telegram_bot_api:
    image: tdlight/telegram-bot-api:latest
    command: --api-id=${API_ID} --api-hash=${API_HASH} --local
    ports:
      - "8081:8081"
    restart: unless-stopped

  python_bot:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      API_TOKEN: ${API_TOKEN}
      LOCAL_API_URL: ${BOT_API:-http://telegram_bot_api:8081}
    depends_on:
      - telegram_bot_api
    networks:
      - bot_network
    restart: unless-stopped

networks:
  bot_network:
