version: '3.3'

services:
  telegram_bot_api:
    build:
      context: .
      dockerfile: Dockerfile.telegram-bot
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
    ports:
      - "8081:8081"
    networks:
      - bot_network

  python_bot:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      API_TOKEN: ${API_TOKEN}
      LOCAL_API_URL: http://localhost:8081  # Обновлено для режима host
      MONGO_URI: mongodb://localhost:27017/telegram_bot_d  # Обновлено для режима host
    depends_on:
      - mongo
      - telegram_bot_api
    network_mode: "host"  # Полный доступ к сети хоста
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    network_mode: "host"  # Полный доступ к сети хоста
    command: mongod --quiet --logpath /dev/null  # Отключаем логи MongoDB

volumes:
  mongo_data:
    driver: local

networks:
  bot_network:
