version: '3.3'

services:
  vpn:
    image: bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TOKEN=${NORDVPN_TOKEN}              # Токен NordVPN
      - CONNECT=Netherlands                 # Сервер для подключения
      - TECHNOLOGY=NordLynx                 # Протокол VPN
      - KILLSWITCH=enabled                  # Блокировка трафика без VPN
      - DNS=1.1.1.1,8.8.8.8                # Cloudflare и Google DNS
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    networks:
      - bot_network
    logging:
      driver: "none"  # Отключаем логи VPN

  telegram_bot_api:
    build:
      context: .
      dockerfile: Dockerfile.telegram-bot
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
    depends_on:
      - vpn
    network_mode: "service:vpn"  # Все запросы через VPN
    restart: unless-stopped
    command: sh -c "sleep 10 && python main.py"  # Задержка для старта VPN

  python_bot:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      API_TOKEN: ${API_TOKEN}
      LOCAL_API_URL: http://localhost:8081  # Используем localhost вместо имени контейнера
      MONGO_URI: mongodb://mongo:27017/telegram_bot_d
    depends_on:
      - mongo
      - telegram_bot_api
      - vpn
    network_mode: "service:vpn"  # Все запросы через VPN
    restart: unless-stopped
    command: sh -c "sleep 15 && python main.py"  # Задержка для старта VPN и API

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bot_network
    command: mongod --quiet --logpath /dev/null  # Отключаем логи MongoDB

volumes:
  mongo_data:
    driver: local

networks:
  bot_network:
