name: Deploy to Server

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Запуск каждые 5 минут

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Deploy to Server
        run: |
          ssh -T ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /var/www/your-project  # Update this path
          git pull origin main
          source /var/www/your-project/venv/bin/activate  # Update this path
          sudo systemctl restart your-service  # Use sudo if required
          EOF